### PR TITLE
Added null check to solve TypeError (NPE)

### PR DESCRIPTION
**Pull request by gaborantal**
This will solve #15 in a naive way, but I checked and it works in my case.

### CODE REVIEW

**Comment by gunar** [comment]
NOT NAIVE. This is JavaScript after all.

Red. Green. Refactor.
This is green so merging.
For the refactor, I would use `lodash`'s `get()`.

THANK YOU SO MUCH! :star:

**Comment by gunar** [comment]
@gaborantal By the way, if you had added "fixes #15" to the commit message, once merging the issue would be automatically closed. Not nitpicking, just saying because you might not know it already. Thanks again!

**Comment by danilaml** [comment]
It looks like it sill affects version hosted on npm.

**Comment by gaborantal** [comment]
@danilaml  Unfortunately, the npm hosted version was not updated for a while.

**Comment by gunar** [comment]
Thanks for the reminder.

**Pull request merged**
